(()=>{
  const $=id=>document.getElementById(id);
  const norm=v=>String(v||'').replace(/\D/g,'');
  const validUIC=v=>{const d=norm(v);if(d.length!==12)return false;let s=0;for(let i=0;i<11;i++){const x=Number(d[i])*(i%2?1:2);s+=Math.floor(x/10)+x%10;}return(10-s%10)%10===Number(d[11]);};
  const fmt=v=>{const d=norm(v).slice(0,12);return d.length===12?d.slice(0,2)+' '+d.slice(2,4)+' '+d.slice(4,8)+' '+d.slice(8,11)+'-'+d.slice(11):v};
  const btn=$('cameraBtn'),input=$('cameraInput');if(!btn||!input)return;
  let status=$('cameraStatus');if(!status){status=document.createElement('div');status.id='cameraStatus';status.className='status';input.closest('.card').appendChild(status);}
  const say=(text,ok=false)=>{status.style.display='block';status.className='status '+(ok?'good':'bad');status.textContent=text;};
  input.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;say('Foto aufgenommen · Wagennummer wird erkannt …');try{if(!window.Tesseract){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}const result=await window.Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')status.textContent='Erkennung '+Math.round((m.progress||0)*100)+' %';}});const text=result?.data?.text||'';const candidates=[];for(const match of text.matchAll(/\d[\d\s.\-/]{9,24}\d/g)){const d=norm(match[0]);for(let i=0;i<=Math.max(0,d.length-12);i++){const c=d.slice(i,i+12);if(c.length===12)candidates.push(c);}}const unique=[...new Set(candidates)],hit=unique.find(validUIC)||unique.find(c=>c.length===12);if(!hit){say('Keine Wagennummer sicher erkannt. Bitte näher fotografieren und nur die Wagennummer ins Bild nehmen.');return;}const field=$('wagonSearch');field.value=fmt(hit);field.dispatchEvent(new Event('input',{bubbles:true}));if(validUIC(hit))say('✓ Erkannt: '+fmt(hit),true);else say('Nummer erkannt, Prüfziffer bitte kontrollieren: '+fmt(hit));}catch(err){say('Erkennung konnte nicht geladen werden. Foto erneut versuchen oder Wagennummer manuell eingeben.');}finally{input.value='';}});
})();